// SPDX-License-Identifier: MIT

pragma solidity >=0.8.0 <0.9.0;

import "./Ballot.sol";

import "@chainlink/contracts/src/v0.8/ChainlinkClient.sol";
import "@chainlink/contracts/src/v0.8/AutomationCompatible.sol";

contract BallotFactory is ChainlinkClient, AutomationCompatibleInterface {
    using Chainlink for Chainlink.Request;

    Ballot[] public ballots;
    bytes32 private jobId;
    address public owner;
    uint256 public s_start;
    uint256 public s_end;
    bool public s_needBallot;
    uint256 private s_fee;

    event RequestEta(bytes32 indexed requestId, uint256 s_end, uint256 s_start);

    receive() external payable {}

    constructor() payable {
        owner = address(this);
        setChainlinkToken(0x326C977E6efc84E512bB9C30f76E30c160eD06FB);
        setChainlinkOracle(0x188b71C9d27cDeE01B9b0dfF5C1aff62E8D6F434);
        jobId = '437d298d210c4fff935dcedb97ea8011';
        s_fee = ((1 * LINK_DIVISIBILITY) / 100) * 5;
        s_needBallot = true;
    }
    
    function deposit() public payable {
        (bool sent, ) = address(this).call{value: msg.value}("");
        require(sent, "Failed to send Ether");
    }

    function request() public returns (bytes32 requestId) {
        Chainlink.Request memory req = buildChainlinkRequest(jobId, address(this), this.fulfill.selector);
        req.add('get', 'http://3.23.88.121:8080/time');
        req.add('path1', 'data,unixSecondsArrivalTime');
        req.add('path2', 'data,unixSecondsStartTime');
        req.addInt('multiply', 1);
        return sendChainlinkRequest(req, s_fee);
    }
    
    function fulfill(bytes32 requestId_, uint256 end, uint256 start) public recordChainlinkFulfillment(requestId_) {
        emit RequestEta(requestId_, end, start);
        s_needBallot = s_end < end;
        s_end = end;
        s_start = start;
    }

    function checkUpkeep(bytes calldata /* checkData */) external view override returns (bool upkeepNeeded, bytes memory /* performData */) {
        upkeepNeeded = false;

        if (block.timestamp > s_end) {
            upkeepNeeded = true;
        }

        if (block.timestamp > s_start) {
            upkeepNeeded = true;
        }

        if (s_needBallot == true) {
            upkeepNeeded = true;
        }

        // We don't use the checkData in this example. The checkData is defined when the Upkeep was registered.
    }

    function performUpkeep(bytes calldata /* performData */) external override {
        //We highly recommend revalidating the upkeep in the performUpkeep function
        Ballot ballot = ballots[ballots.length - 1];

        if (block.timestamp > s_end) {
            request();
        }

        if (block.timestamp > s_start) {
            ballot.endVotingPeriod();
            s_start = 1099511627775; // now it won't trip the conditional and will reset when request() is fulfilled
        }

        if (s_needBallot == true) {
            create2();
        }
        // We don't use the performData in this example. The performData is generated by the Keeper's call to your checkUpkeep function
    }

    function create2() public {
        Ballot ballot = new Ballot(s_end, s_start);
        s_needBallot = false;
        ballots.push(ballot);
    }

    function viewEta() public view returns (uint256, uint256) {
        return (s_end, s_start);
    }

    function getBallot(uint _index) public view returns (
        address ballotAddress,
        uint winningProposal_,
        string memory winnerName_) {
        Ballot ballot = ballots[_index];
        return (ballot.ballotAddress(),
            ballot.winningProposal(), 
            ballot.winnerName());
    }

    function getCurrentBallot() public view returns (
        address ballotAddress,
        uint winningProposal_,
        string memory winnerName_,
        address[] memory ballotVoters_,
        bytes[] memory ballotVotersInfo_,
        uint amountOfBallots) {
        Ballot ballot = ballots[ballots.length - 1];
        return (ballot.ballotAddress(), 
            ballot.winningProposal(), 
            ballot.winnerName(), 
            ballot.ballotVoters(), 
            ballot.ballotVotersInfo(), 
            amountOfBallots);
    }

    function voteCurrentBallot(uint8 _vote) public {
        Ballot ballot = ballots[ballots.length - 1];
        ballot.vote(_vote, msg.sender);
    }
}